In [2]:
pip install astropy

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.5 MB ? eta -:--:--
   - -----------------------------

In [2]:
from pypdf import PdfReader

def pdf_read(path):
    read_d=PdfReader(path)
    p_obj=[]
    for i in range(len(read_d.pages)):
        pdf_page=read_d.pages[i]
        p_obj.append(pdf_page.extract_text().split('\n'))
    # p_obj.append(read_d.pages[i].extract_text())  
    return p_obj

# pdf_read('C://Users/workt/OneDrive/ドキュメント/spec_cia.pdf')
# pdf_read('C://Users/workt/OneDrive/ドキュメント/AMD.pdf')
# pdf_read('C://Users/workt/Downloads/助産師.pdf')
pdf_read('C://Users/workt/Downloads/医者.pdf')

# dictonary=['電圧','電流','温度','回路']

[['DKIX01AH.smd  Page 1 21/12/22 16:46  v4.00',
  '注意事項',
  '1．試験問題の数は75問で解答時間は正味 /c2692時間45分である。',
  '2．解答方法は次のとおりである。',
  '⑴ に訂適適行え例/c2691に訂適適え適、に訂適適行え例/c2692に訂適適え適の問題ではａからｅまでの/c2695つの選択肢があるので、そのう',
  'ち質問に適した選択肢をに訂適適行え例/c2691に訂適適え適では/c2691つ、に訂適適行え例/c2692に訂適適え適では/c2692つ選び答案用紙に記入',
  'すること。なお、に訂適適行え例/c2691に訂適適え適の質問には/c2692つ以上解答した場合は誤りとする。',
  'に訂適適行え例/c2692に訂適適え適の質問には/c2691つ又は/c2693つ以上解答した場合は誤りとする。',
  'に訂適適行え例/c2691に訂適適え適101 医業が行えるのはどれか｡',
  'ａ 合格発表日以降',
  'ｂ 合格証書受領日以降',
  'ｃ 免許申請日以降',
  'ｄ 臨床研修開始日以降',
  'ｅ 医籍登録日以降',
  'に訂適適行え例/c2692に訂適適え適102 医籍訂正の申請が必要な',
  'のはどれか。/c2692つ選べ。',
  'ａ 氏名変更時',
  'ｂ 住所地変更時',
  'ｃ 勤務先変更時',
  'ｄ 診療所開設時',
  'ｅ 本籍地都道府県変更時',
  'に訂適適行え例/c2691に訂適適え適の正解は｢ｅ｣であるから答案用紙のｅ をマークすればよい。',
  'ｃ',
  '答案用紙②の場合、',
  'ａ',
  'ｂ',
  'ｄ',
  'ｄａ ｂ',
  '答案用紙①の場合、',
  'ｃ',
  'ａ ｂ ｃ ｄ ｅ101',
  '101',
  '粟 ａ',
  'ｂ',
  'ｃ',
  'ｄ',
  'ｅ',
  '或',
  '101 101',
  'に訂適適行え例/c2692に訂適適え適の正解は｢ａ｣と｢ｅ｣であるから答案用紙のａ と ｅ をマークすれ',
  'ばよい。',
  'ｃ',
  'ｃ',
  '答案用紙②の場合、',
  'ｂ',
  'ｄ',
  '答案用紙①の場合、',
 

In [14]:
import torch.nn as nn
import torch

class analys:
    def tfmodel(self):
        self.model=nn.Transformer
        return self.model

con=analys().tfmodel()
con

torch.nn.modules.transformer.Transformer

In [8]:
import torch.nn as nn
import torch

encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8)
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)
# ソースデータの特徴量=src
src = torch.rand(20, 32, 512)
out = transformer_encoder(src)
# print(out)

decoder_layer = nn.TransformerDecoderLayer(d_model=512, nhead=8)
transformer_decoder = nn.TransformerDecoder(decoder_layer, num_layers=6)
# トレーニングデータの特徴量=tgt
memory = torch.rand(20, 32, 512)
tgt = torch.rand(20, 32, 512)
out = transformer_decoder(tgt, memory)
print(out)

C:\Users\workt\anaconda3\envs\gpt\Lib\site-packages\torch\nn\modules\transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


tensor([[[-0.1407, -0.7260,  0.9238,  ...,  1.7414,  0.1831, -0.4542],
         [ 0.6449, -1.0648,  0.4984,  ...,  2.0073, -0.8339,  0.2615],
         [ 0.3122, -1.7784,  0.0457,  ...,  1.9814,  0.3633,  0.1453],
         ...,
         [ 0.3846, -1.8899,  0.4469,  ...,  1.7511, -1.5006, -0.2963],
         [ 0.1377, -2.0388,  0.1456,  ...,  1.9324,  0.1434, -0.8861],
         [ 0.1117, -1.5085,  0.1226,  ...,  1.5043, -0.4894, -0.7436]],

        [[ 1.1500, -1.5997,  0.5187,  ...,  1.4451,  0.4382,  0.0046],
         [ 0.5533, -1.2592,  0.0974,  ...,  0.8240, -0.0872, -0.5596],
         [ 0.5358, -1.3967,  0.1991,  ...,  2.1022,  0.3527, -0.4232],
         ...,
         [ 0.4518, -1.4386, -0.1743,  ...,  2.1100, -0.9435,  0.0724],
         [ 0.3864, -2.0291,  0.5771,  ...,  1.5383, -0.7723, -0.3892],
         [-0.1728, -1.4389,  0.2567,  ...,  1.3980, -0.5775, -0.8310]],

        [[ 0.9481, -0.9892,  0.6346,  ...,  1.2789, -0.2201, -0.9812],
         [ 0.2998, -1.6442,  0.0146,  ...,  1

In [36]:
# 必要なライブラリをインストール
# pip install torch transformers

from transformers import BartForConditionalGeneration, BartTokenizer

# BARTモデルとトークナイザーをロード
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)

# # 要約するテキスト
# text = """
# PyTorch is an open-source machine learning framework that accelerates the path from research prototyping to production deployment. 
# It is used extensively in both academia and industry, with applications ranging from natural language processing to computer vision.
# """
text=str(pdf_read('C://Users/workt/OneDrive/ドキュメント/AMD.pdf'))
# text=str(pdf_read('C://Users/workt/Downloads/助産師.pdf'))

# テキストをトークン化してモデルの入力に変換
inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", max_length=1024, truncation=True)

# 要約を生成
summary_ids = model.generate(inputs, max_length=130, min_length=30, length_penalty=2.0, num_beams=4, early_stopping=True)

# 結果をデコードして表示
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
print("Summary:", summary)


Summary: summarize: [['AMD       特   日 japan.xilinx.com', 'AMD Artix™ 7 FPGA', 'DS181 (v1.27.1) 2024 年 7 有 3   Japan', '-1LI -2L -0.95V -1.9V -2.0V'], '-3LI -3L -2V' });.


In [8]:
import torch.nn as nn
import torch

m = nn.ReflectionPad1d(2)
input = torch.arange(8, dtype=torch.float).reshape(1, 2, 4)
input
m(input)
# using different paddings for different sides
m = nn.ReflectionPad1d((3, 1))
m(input)

tensor([[[3., 2., 1., 0., 1., 2., 3., 2.],
         [7., 6., 5., 4., 5., 6., 7., 6.]]])

In [9]:
m = nn.ReflectionPad3d(1)
input = torch.arange(8, dtype=torch.float).reshape(1, 1, 2, 2, 2)
m(input)

tensor([[[[[7., 6., 7., 6.],
           [5., 4., 5., 4.],
           [7., 6., 7., 6.],
           [5., 4., 5., 4.]],

          [[3., 2., 3., 2.],
           [1., 0., 1., 0.],
           [3., 2., 3., 2.],
           [1., 0., 1., 0.]],

          [[7., 6., 7., 6.],
           [5., 4., 5., 4.],
           [7., 6., 7., 6.],
           [5., 4., 5., 4.]],

          [[3., 2., 3., 2.],
           [1., 0., 1., 0.],
           [3., 2., 3., 2.],
           [1., 0., 1., 0.]]]]])

In [10]:
m = nn.ConstantPad3d(3, 3.5)
input = torch.randn(16, 3, 10, 20, 30)
output = m(input)
# using different paddings for different sides
m = nn.ConstantPad3d((3, 3, 6, 6, 0, 1), 3.5)
output = m(input)
# print(output)

In [14]:
m = nn.CircularPad3d(3)
input = torch.randn(16, 3, 8, 320, 480)
output = m(input)
# using different paddings for different sides
m = nn.CircularPad3d((3, 3, 6, 6, 1, 1))
output = m(input)
# print(output)

In [ ]:
pip install idna